name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main  # Trigger this workflow only when changes are pushed to the `main` branch

jobs:
  build-deploy:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
    # Step 1: Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker to use Minikube's Docker daemon
    - name: Set up Docker to use Minikube's environment
      shell: cmd
      run: |
        echo Configuring Docker to use Minikube's daemon...
        eval $(minikube docker-env)

    # Step 3: Build Docker image
    - name: Build Docker image
      shell: cmd
      run: |
        docker build -t ali464/my-front-end-app:latest .

    # Step 4: Login to Docker Hub
    - name: Login to Docker Hub
      shell: cmd
      run: |
        echo %DOCKER_PASSWORD% | docker login -u %DOCKER_USERNAME% --password-stdin

    # Step 5: Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      shell: cmd
      run: |
        docker push ali464/my-front-end-app:latest

    # Step 6: Deploy to Minikube (Kubernetes)
    - name: Deploy to Minikube
      shell: cmd
      run: |
        kubectl apply -f deployement.yaml
        kubectl apply -f service.yaml
